name: "Black Duck Snippet Scanner"
description: "Will use Black Duck API to scan the given hashes"
author: Jouni Lehto
branding:
  icon: code
  color: blue
inputs:
  blackduck_log_level:
    description: Logging level
    default: DEBUG
    required: false
  blackduck_url:
    description: "Black Duck URL"
    required: true
  blackduck_apiToken:
    description: "Black Duck Access token"
    required: true
  blackduck_outputFile:
    description: "Filename with path where it will be created, example: github.workspace/blackduck-snippet.sarif.json (default)"
    default: ${{github.workspace}}/blackduck-snippet.sarif.json
    required: false
  github_url:
    description: "GitHub URL"
    required: true
  github_apiToken:
    description: "GitHub Access token"
    required: true
  github_repo:
    description: "GitHub repository"
    required: true
  github_pull_request_id:
    description: "GitHub Pull request ID"
    required: true
  github_prComment:
    description: "false will export json file as a response."
    default: "false"
    required: false
  github_prCommentGroupped:
    description: "false create comment for each finding"
    default: "false"
    required: false
  github_sarif:
    description: "true create sarif format report"
    default: "true"
    required: false
  github_toolNameforSarif:
    description: "Tool name for Sarif -results. Defaul is \"Black Duck Snippet\""
    default: "Black Duck Snippet"
    required: false

runs:
  using: composite
  steps:
    # Run the Python script
    - run: |
        pip install -r ${{github.action_path}}/requirements.txt
        python3 ${{github.action_path}}/bd_snippet_scanner.py --toolNameforSarif="${{inputs.github_toolNameforSarif}}" --sarif=${{inputs.github_sarif}} --action_path="${{github.action_path}}" --url="${{inputs.blackduck_url}}" --token="${{inputs.blackduck_apiToken}}" --gittoken="${{inputs.github_apiToken}}" --repo="${{inputs.github_repo}}" --prID="${{inputs.github_pull_request_id}}" --group="${{inputs.github_prCommentGroupped}}" --prComment="${{inputs.github_prComment}}" --result_file="${{inputs.blackduck_outputFile}}"
        cat snippet_results.md >> $GITHUB_STEP_SUMMARY
        rm snippet_results.md
      shell: bash
